name: todo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.3.0
  cloud_firestore: ^4.0.1
  firebase_auth_web: 5.1.3
  firebase_auth: 4.1.5
  firebase_storage: ^11.0.1
  flutter_riverpod: ^1.0.4
  gap: ^2.0.0
  flutter_svg: ^1.1.6
  flutter_highlighter: ^0.1.1
  flutter_highlight: ^0.7.0
  common:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: common
  sandbox:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: sandbox
  providers:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: providers
  auth:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: auth
  widgets:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: widgets
  theme:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: theme
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true